"""remove always_link_preview

Revision ID: 1f1aabfe1f6b
Revises: 5d6dfa7afc4d
Create Date: 2026-05-10 23:19:47.967639

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f1aabfe1f6b"
down_revision: Union[str, None] = "5d6dfa7afc4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("targets", "always_link_preview", schema="wftb")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.add_column(
        "targets",
        sa.Column("always_link_preview", sa.Boolean(), nullable=True),
        schema="wftb",
    )
    conn.execute(sa.text("UPDATE wftb.targets SET always_link_preview=false;"))
    op.alter_column(
        "targets",
        "always_link_preview",
        existing_type=sa.Boolean(),
        nullable=False,
        schema="wftb",
    )
    # ### end Alembic commands ###
