name: Stop app
run-name: Stop app at ${{ inputs.target }} env

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Environment"
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - prod

jobs:
  stop:
    runs-on: ubuntu-latest
    name: Stop app
    steps:
      - name: Stop
        uses: appleboy/ssh-action@v1.0.0
        env:
          B_ENV: ${{ inputs.target }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            echo "-------- Try to stop wftb-${{ env.B_ENV }} container"
            docker stop wftb-${{ env.B_ENV }} || true
